{{- if .Values.database.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-service.fullname" . }}-postgres
  labels:
    {{- include "auth-service.database.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  clusterIP: None
  ports:
  - port: {{ .Values.database.service.port }}
    targetPort: postgres
    protocol: TCP
    name: postgres
  selector:
    {{- include "auth-service.database.selectorLabels" . | nindent 4 }}
{{- end }}
